### ISSUE TITLE
Table of contents is "cramped" looking

### ISSUE THREAD

**Issue by Aariq** [cct-datascience/ggplot2-workshop-series#10]
Because of the long workshop titles, the table of contents looks cramped.  Possible solutions:

- make sidebar wider
- use navbar organization with dropdown menus (e.g. at the bottom of this section: https://quarto.org/docs/websites/website-navigation.html#hybrid-navigation)
- collapse sections by default with `collapse-level: 1` (only hides the mess until a user clicks on a year)
- use alternative, short titles just for sidebar like so:

``` yaml
sidebar:
  contents:
    - "Professional Data Viz"
      href: "2024/02-design/index.qmd"
```

**Comment by KristinaRiemer** [comment]
I like the last option, but I think I'm not doing the formatting correctly? 

```
website:
  title: "Intermediate ggplot2 workshop series"
  repo-url: "https://github.com/cct-datascience/ggplot2-workshop-series"
  repo-actions: ["source", "issue"]
  sidebar: 
    style: "docked"
    search: true
    logo: logo.png
    contents:
      - section: "Upcoming series"
        href: "2024/index.qmd"
        contents:
          - "Session 1 - Foundations"
            href: "2024/01-foundations/index.qmd"
          - "Session 2 - Design"
            href: "2024/02-design/index.qmd"
          - "Session 3 - Extensions"
            href: "2024/03-extensions/index.qmd"
      - section: "2023"
        contents:
          - "2023/01-foundations/index.qmd"
          - "2023/02-publication-quality-figs/index.qmd"
          - "2023/03-extensions/index.qmd"
```

**Comment by KristinaRiemer** [comment]
This works now, but the subsections, e.g., "Session 1 - Foundations" are no longer clickable links. 

```
website:
  title: "Intermediate ggplot2 workshop series"
  repo-url: "https://github.com/cct-datascience/ggplot2-workshop-series"
  repo-actions: ["source", "issue"]
  sidebar: 
    style: "docked"
    search: true
    logo: logo.png
    contents:
      - section: "Upcoming series"
        href: "2024/index.qmd"
        contents:
          - section: "Session 1 - Foundations"
            href: "2024/01-foundations/index.qmd"
          - section: "Session 2"
            href: "2024/02-design/index.qmd"
          - section: "Session 3"
            href: "2024/03-extensions/index.qmd"
      - section: "2023"
        contents:
          - "2023/01-foundations/index.qmd"
          - "2023/02-publication-quality-figs/index.qmd"
          - "2023/03-extensions/index.qmd"
```
Also, @Aariq you'd be able to figure out how to get this to work way faster than me, so I'll stop fiddling. But I think this approach works!
